
services:
  haproxy:
    image: app_haproxy
    networks:
      cangnet:
        ipv4_address: 172.30.0.2
    container_name: haproxy
    ports:
      - "80:80"

  redis:
    image: redis:latest
    networks:
      cangnet:
        ipv4_address: 172.30.0.3
    container_name: redis
    depends_on:
      - haproxy

  node1:
    image: app_web
    networks:
      cangnet:
        ipv4_address: 172.30.0.4
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    container_name: node1
    depends_on:
      - redis

  node2:
    image: app_web
    networks:
      cangnet:
        ipv4_address: 172.30.0.5
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    container_name: node2
    depends_on:
      - node1


  node3:
    image: app_web
    networks:
      cangnet:
        ipv4_address: 172.30.0.6
    environment:
      - REDIS_HOST=172.30.0.3
      - REDIS_PORT=6379
    container_name: node3
    depends_on:
      - node2

networks:
  cangnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24


